/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as LangProductsIndexRouteImport } from './routes/$lang/products/index'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as LangProductsProductIdRouteImport } from './routes/$lang/products/$productId'
import { Route as LangDemoStartServerFuncsRouteImport } from './routes/$lang/demo/start.server-funcs'
import { Route as LangDemoStartApiRequestRouteImport } from './routes/$lang/demo/start.api-request'
import { Route as LangDemoApiNamesRouteImport } from './routes/$lang/demo/api.names'
import { Route as LangDemoStartSsrIndexRouteImport } from './routes/$lang/demo/start.ssr.index'
import { Route as LangDemoStartSsrSpaModeRouteImport } from './routes/$lang/demo/start.ssr.spa-mode'
import { Route as LangDemoStartSsrFullSsrRouteImport } from './routes/$lang/demo/start.ssr.full-ssr'
import { Route as LangDemoStartSsrDataOnlyRouteImport } from './routes/$lang/demo/start.ssr.data-only'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const LangProductsIndexRoute = LangProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LangRoute,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LangProductsProductIdRoute = LangProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => LangRoute,
} as any)
const LangDemoStartServerFuncsRoute =
  LangDemoStartServerFuncsRouteImport.update({
    id: '/demo/start/server-funcs',
    path: '/demo/start/server-funcs',
    getParentRoute: () => LangRoute,
  } as any)
const LangDemoStartApiRequestRoute = LangDemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => LangRoute,
} as any)
const LangDemoApiNamesRoute = LangDemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => LangRoute,
} as any)
const LangDemoStartSsrIndexRoute = LangDemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => LangRoute,
} as any)
const LangDemoStartSsrSpaModeRoute = LangDemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => LangRoute,
} as any)
const LangDemoStartSsrFullSsrRoute = LangDemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => LangRoute,
} as any)
const LangDemoStartSsrDataOnlyRoute =
  LangDemoStartSsrDataOnlyRouteImport.update({
    id: '/demo/start/ssr/data-only',
    path: '/demo/start/ssr/data-only',
    getParentRoute: () => LangRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/products/$productId': typeof LangProductsProductIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/$lang/products': typeof LangProductsIndexRoute
  '/$lang/demo/api/names': typeof LangDemoApiNamesRoute
  '/$lang/demo/start/api-request': typeof LangDemoStartApiRequestRoute
  '/$lang/demo/start/server-funcs': typeof LangDemoStartServerFuncsRoute
  '/$lang/demo/start/ssr/data-only': typeof LangDemoStartSsrDataOnlyRoute
  '/$lang/demo/start/ssr/full-ssr': typeof LangDemoStartSsrFullSsrRoute
  '/$lang/demo/start/ssr/spa-mode': typeof LangDemoStartSsrSpaModeRoute
  '/$lang/demo/start/ssr': typeof LangDemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/$lang': typeof LangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$lang/products/$productId': typeof LangProductsProductIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/$lang/products': typeof LangProductsIndexRoute
  '/$lang/demo/api/names': typeof LangDemoApiNamesRoute
  '/$lang/demo/start/api-request': typeof LangDemoStartApiRequestRoute
  '/$lang/demo/start/server-funcs': typeof LangDemoStartServerFuncsRoute
  '/$lang/demo/start/ssr/data-only': typeof LangDemoStartSsrDataOnlyRoute
  '/$lang/demo/start/ssr/full-ssr': typeof LangDemoStartSsrFullSsrRoute
  '/$lang/demo/start/ssr/spa-mode': typeof LangDemoStartSsrSpaModeRoute
  '/$lang/demo/start/ssr': typeof LangDemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/products/$productId': typeof LangProductsProductIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/$lang/products/': typeof LangProductsIndexRoute
  '/$lang/demo/api/names': typeof LangDemoApiNamesRoute
  '/$lang/demo/start/api-request': typeof LangDemoStartApiRequestRoute
  '/$lang/demo/start/server-funcs': typeof LangDemoStartServerFuncsRoute
  '/$lang/demo/start/ssr/data-only': typeof LangDemoStartSsrDataOnlyRoute
  '/$lang/demo/start/ssr/full-ssr': typeof LangDemoStartSsrFullSsrRoute
  '/$lang/demo/start/ssr/spa-mode': typeof LangDemoStartSsrSpaModeRoute
  '/$lang/demo/start/ssr/': typeof LangDemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/admin'
    | '/admin/login'
    | '/$lang/'
    | '/admin/'
    | '/$lang/products/$productId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/$lang/products'
    | '/$lang/demo/api/names'
    | '/$lang/demo/start/api-request'
    | '/$lang/demo/start/server-funcs'
    | '/$lang/demo/start/ssr/data-only'
    | '/$lang/demo/start/ssr/full-ssr'
    | '/$lang/demo/start/ssr/spa-mode'
    | '/$lang/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/$lang'
    | '/admin'
    | '/$lang/products/$productId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/$lang/products'
    | '/$lang/demo/api/names'
    | '/$lang/demo/start/api-request'
    | '/$lang/demo/start/server-funcs'
    | '/$lang/demo/start/ssr/data-only'
    | '/$lang/demo/start/ssr/full-ssr'
    | '/$lang/demo/start/ssr/spa-mode'
    | '/$lang/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/admin'
    | '/admin/login'
    | '/$lang/'
    | '/admin/'
    | '/$lang/products/$productId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/$lang/products/'
    | '/$lang/demo/api/names'
    | '/$lang/demo/start/api-request'
    | '/$lang/demo/start/server-funcs'
    | '/$lang/demo/start/ssr/data-only'
    | '/$lang/demo/start/ssr/full-ssr'
    | '/$lang/demo/start/ssr/spa-mode'
    | '/$lang/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/products/': {
      id: '/$lang/products/'
      path: '/products'
      fullPath: '/$lang/products'
      preLoaderRoute: typeof LangProductsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/products/$productId': {
      id: '/$lang/products/$productId'
      path: '/products/$productId'
      fullPath: '/$lang/products/$productId'
      preLoaderRoute: typeof LangProductsProductIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/demo/start/server-funcs': {
      id: '/$lang/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/$lang/demo/start/server-funcs'
      preLoaderRoute: typeof LangDemoStartServerFuncsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/demo/start/api-request': {
      id: '/$lang/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/$lang/demo/start/api-request'
      preLoaderRoute: typeof LangDemoStartApiRequestRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/demo/api/names': {
      id: '/$lang/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/$lang/demo/api/names'
      preLoaderRoute: typeof LangDemoApiNamesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/demo/start/ssr/': {
      id: '/$lang/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/$lang/demo/start/ssr'
      preLoaderRoute: typeof LangDemoStartSsrIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/demo/start/ssr/spa-mode': {
      id: '/$lang/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/$lang/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof LangDemoStartSsrSpaModeRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/demo/start/ssr/full-ssr': {
      id: '/$lang/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/$lang/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof LangDemoStartSsrFullSsrRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/demo/start/ssr/data-only': {
      id: '/$lang/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/$lang/demo/start/ssr/data-only'
      preLoaderRoute: typeof LangDemoStartSsrDataOnlyRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
  LangProductsProductIdRoute: typeof LangProductsProductIdRoute
  LangProductsIndexRoute: typeof LangProductsIndexRoute
  LangDemoApiNamesRoute: typeof LangDemoApiNamesRoute
  LangDemoStartApiRequestRoute: typeof LangDemoStartApiRequestRoute
  LangDemoStartServerFuncsRoute: typeof LangDemoStartServerFuncsRoute
  LangDemoStartSsrDataOnlyRoute: typeof LangDemoStartSsrDataOnlyRoute
  LangDemoStartSsrFullSsrRoute: typeof LangDemoStartSsrFullSsrRoute
  LangDemoStartSsrSpaModeRoute: typeof LangDemoStartSsrSpaModeRoute
  LangDemoStartSsrIndexRoute: typeof LangDemoStartSsrIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangProductsProductIdRoute: LangProductsProductIdRoute,
  LangProductsIndexRoute: LangProductsIndexRoute,
  LangDemoApiNamesRoute: LangDemoApiNamesRoute,
  LangDemoStartApiRequestRoute: LangDemoStartApiRequestRoute,
  LangDemoStartServerFuncsRoute: LangDemoStartServerFuncsRoute,
  LangDemoStartSsrDataOnlyRoute: LangDemoStartSsrDataOnlyRoute,
  LangDemoStartSsrFullSsrRoute: LangDemoStartSsrFullSsrRoute,
  LangDemoStartSsrSpaModeRoute: LangDemoStartSsrSpaModeRoute,
  LangDemoStartSsrIndexRoute: LangDemoStartSsrIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
